global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  
  ################## Prometheus ##################
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  ################## Node Exporter ##################

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['prometheus-server.josuecarames.com:9100', 'mysql.josuecarames.com:9100', 'uptime-server.josuecarames.com:9100', 'traefik.josuecarames.com:9100', 'portainer-server.josuecarames.com:9100', 'homepage.josuecarames.com:9100', 'authentik-server.josuecarames.com:9100', 'dns.josuecarames.com:9100', 'dns-backup.josuecarames.com:9100', 'cloudflare.josuecarames.com:9100', 'cloudflare-backup.josuecarames.com:9100', 'www-server.josuecarames.com:9100', 'ntfy-server.josuecarames.com:9100', 'vscode-server.josuecarames.com:9100', 'ollama-server.josuecarames.com:9100', 'sdr-server.josuecarames.com:9100']

  ################## cAdvisor ##################

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['prometheus-server.josuecarames.com:8080', 'mysql.josuecarames.com:8080', 'uptime-server.josuecarames.com:8080', 'traefik.josuecarames.com:8080', 'portainer-server.josuecarames.com:8080', 'homepage.josuecarames.com:8080', 'authentik-server.josuecarames.com:8080', 'dns.josuecarames.com:8080', 'dns-backup.josuecarames.com:8080', 'cloudflare.josuecarames.com:8080', 'cloudflare-backup.josuecarames.com:8080', 'www-server.josuecarames.com:8080', 'ntfy-server.josuecarames.com:8080', 'vscode-server.josuecarames.com:8080', 'ollama-server.josuecarames.com:8080', 'sdr-server.josuecarames.com:8080']

  ################## MySQL ##################

  - job_name: mysql # To get metrics about the mysql exporter’s targets
    static_configs:
      - targets:
        # All mysql hostnames or unix sockets to monitor.
        - mysql.josuecarames.com:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # The mysqld_exporter host:port
        replacement: mysql.josuecarames.com:9104

  ################## NVIDIA GPU ##################
  
  - job_name: 'nvidia_gpu'
    static_configs:
      - targets: ['ollama-server.josuecarames.com:9835']